### ISSUE TITLE
Unify the "display" format and "parse" format for `HctlTreeNode`

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-hctl-model-checker#10]
At the moment, the output of `display` in `HctlTreeNode` is slightly different compared to the format that can be actually parsed. The displayed format is a bit more readable, but is also a bit confusing, since it cannot be actually converted back to a formula.

**Comment by ondrej33** [comment]
Closed by f7858445cc29af8ffd2f6262c40bdfc94dd33aee.
