### ISSUE TITLE
Sanitization/desanitization of BDD

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-hctl-model-checker#5]
Right now, the BDDs resulting from the model checking process (or BDDs entering the model checking methods) need to admit the symbolic variables that encode additional HCTL state variables. However, this means the BDDs are incompatible with BDDs produced by a "standard" `SymbolicAsyncGraph`. This means the HCTL model checker generally cannot "share" results with other tools in the biodivine tool-chain (either importing or exporting).

However, it is possible to "sanitize" these BDDs as demonstrated [here](https://github.com/sybila/biodivine-bn-classifier/commit/bc5132c147d729207e66e29eca8fcae73c7178ab) such that they are compatible with the default `SymbolicAsyncGraph` representation.

It would thus be good to include this functionality in the model checker library as well.

**Comment by ondrej33** [comment]
This should be resolved through #6 and #7. The standard model-checking procedure now automatically applies this "sanitization" to the resulting BDDs. Versions of the model-checking functions without sanitizing are also provided, as they are useful for some contexts.
