### ISSUE TITLE
Allow "raw sets" as atomic propositions/subformulae

### ISSUE THREAD

**Issue by daemontus** [sybila/biodivine-hctl-model-checker#8]
At the moment, we can only model check HCTL with a known "syntactic" atomic propositions. However, in theory, nothing stops us from giving the model checker an arbitrary (coloured) set as an atomic proposition.

This has two big advantages:
 - A formula that is already computed can be reused in subsequent computations. Simply replace the computed sub-formula with such a "raw" proposition.
 - Results of other analysis can be incorporated into model checking. We (partially) do this for attractors/fixed-points anyway (i.e. we use different algorithms to compute these). This would allow us to make this available as part of the public API.
 
There are two general options for doing this (so far):
 - \[A\] Allow general strings (e.g. `"foo"`) as atomic propositions, and then allow specifying some kind of "AP context" during model checking (i.e. a map which assigns each string proposition a set of states). 
 - \[B\] Add a "HCTL tree node" variant which contains the raw set and can be part of a larger formula. 
 
Variant *B* is probably a bit easier to implement, but also a bit less user friendly. Any formula that uses the raw proposition has to be created in code and cannot be parsed. Meanwhile, option *A* is a bit more complicated to implement (changes to parser, extra "context", etc.), but a bit more user friendly since it is easier to input properties that mix HCTL with raw sets.

**Comment by ondrej33** [comment]
This should now be resolved through #9.
